@host = https://localhost:7275

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMDIyM2JlMS1iOGZiLTRkZTItYmZhZC0yZDNiNTY1MjNhYzYiLCJnaXZlbl9uYW1lIjoiS3lsZSIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJqdGkiOiJjY2M0OWQ4OS0wMDg5LTRjMzYtOGFlNy0yOTcwMjI1NjJkMGMiLCJ1bmlxdWVfbmFtZSI6IjMwMjIzYmUxLWI4ZmItNGRlMi1iZmFkLTJkM2I1NjUyM2FjNiIsImV4cCI6MTY2OTQwNTk1NSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.kwOj_QPMHmyLv6bkFo-lAA6GZmtKtErJn_c2xiwOVRs