@host = https://localhost:7275
@hostId = 00000000-0000-0000-0000-000000000000

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxODIwZDA1ZS0xMmQ4LTQ5YjUtOGY0NS05N2JiYzg2NmI3NzYiLCJnaXZlbl9uYW1lIjoiS3lsZSIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJqdGkiOiI3ZjJmNjg5Ny1kYTkzLTQzZDctYTJmYi03NmU1MjM1N2Q2MjkiLCJ1bmlxdWVfbmFtZSI6IjE4MjBkMDVlLTEyZDgtNDliNS04ZjQ1LTk3YmJjODY2Yjc3NiIsImV4cCI6MTY2OTQ4NDUwMCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.TbFkROBe4Vx1rh4NsIHfgGJOVgTSoyNH_04NckF_DAk

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 4.5,
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}